// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsq56jYHwtIt5EoMttroRq2l-d8EffCo',
    appId: '1:803759046672:web:eaa104985b36a388090a95',
    messagingSenderId: '803759046672',
    projectId: 'pamtion-f8f4c',
    authDomain: 'pamtion-f8f4c.firebaseapp.com',
    storageBucket: 'pamtion-f8f4c.appspot.com',
    measurementId: 'G-30KH7VF11F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyoEUv8mOIlXk86QFMDlcrizKntuebf6s',
    appId: '1:803759046672:ios:b303698cc40fa37c090a95',
    messagingSenderId: '803759046672',
    projectId: 'pamtion-f8f4c',
    storageBucket: 'pamtion-f8f4c.appspot.com',
    iosBundleId: 'com.example.pamtionPc.RunnerTests',
  );
}
